### ISSUE TITLE
Yake Demo Broken Link

### ISSUE THREAD

**Issue by Btibert3** [koaning/tokenwiser#57]
In the docs, the link for the Yake demo appears to be broken.  

http://yake.inesctec.pt/demo/url

I am not sure what it pointed to previously, but from the base site, it appears that there are two tools to choose from.

- http://yake.inesctec.pt/demo/user
- http://yake.inesctec.pt/demo/url

**Comment by koaning** [comment]
Confirmed. 

Feel free to make a PR if you're up for it. Otherwise I'll pick this up whenever time allows.
